/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/upf/code/catkin_ws/src/ros_lab2task2a/srv/RbuttonStatus.srv
 *
 */


#ifndef ROS_LAB2TASK2A_MESSAGE_RBUTTONSTATUS_H
#define ROS_LAB2TASK2A_MESSAGE_RBUTTONSTATUS_H

#include <ros/service_traits.h>


#include <ros_lab2task2a/RbuttonStatusRequest.h>
#include <ros_lab2task2a/RbuttonStatusResponse.h>


namespace ros_lab2task2a
{

struct RbuttonStatus
{

typedef RbuttonStatusRequest Request;
typedef RbuttonStatusResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RbuttonStatus
} // namespace ros_lab2task2a


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_lab2task2a::RbuttonStatus > {
  static const char* value()
  {
    return "e9084cbdc2bffe2899fcce39fcb32066";
  }

  static const char* value(const ::ros_lab2task2a::RbuttonStatus&) { return value(); }
};

template<>
struct DataType< ::ros_lab2task2a::RbuttonStatus > {
  static const char* value()
  {
    return "ros_lab2task2a/RbuttonStatus";
  }

  static const char* value(const ::ros_lab2task2a::RbuttonStatus&) { return value(); }
};


// service_traits::MD5Sum< ::ros_lab2task2a::RbuttonStatusRequest> should match 
// service_traits::MD5Sum< ::ros_lab2task2a::RbuttonStatus > 
template<>
struct MD5Sum< ::ros_lab2task2a::RbuttonStatusRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_lab2task2a::RbuttonStatus >::value();
  }
  static const char* value(const ::ros_lab2task2a::RbuttonStatusRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_lab2task2a::RbuttonStatusRequest> should match 
// service_traits::DataType< ::ros_lab2task2a::RbuttonStatus > 
template<>
struct DataType< ::ros_lab2task2a::RbuttonStatusRequest>
{
  static const char* value()
  {
    return DataType< ::ros_lab2task2a::RbuttonStatus >::value();
  }
  static const char* value(const ::ros_lab2task2a::RbuttonStatusRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_lab2task2a::RbuttonStatusResponse> should match 
// service_traits::MD5Sum< ::ros_lab2task2a::RbuttonStatus > 
template<>
struct MD5Sum< ::ros_lab2task2a::RbuttonStatusResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_lab2task2a::RbuttonStatus >::value();
  }
  static const char* value(const ::ros_lab2task2a::RbuttonStatusResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_lab2task2a::RbuttonStatusResponse> should match 
// service_traits::DataType< ::ros_lab2task2a::RbuttonStatus > 
template<>
struct DataType< ::ros_lab2task2a::RbuttonStatusResponse>
{
  static const char* value()
  {
    return DataType< ::ros_lab2task2a::RbuttonStatus >::value();
  }
  static const char* value(const ::ros_lab2task2a::RbuttonStatusResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_LAB2TASK2A_MESSAGE_RBUTTONSTATUS_H
