/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/upf/code/catkin_ws/src/ros_lab2task2a/msg/Rencoder.msg
 *
 */


#ifndef ROS_LAB2TASK2A_MESSAGE_RENCODER_H
#define ROS_LAB2TASK2A_MESSAGE_RENCODER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace ros_lab2task2a
{
template <class ContainerAllocator>
struct Rencoder_
{
  typedef Rencoder_<ContainerAllocator> Type;

  Rencoder_()
    : Rencoder()
    , rotations(0)
    , on(false)  {
    }
  Rencoder_(const ContainerAllocator& _alloc)
    : Rencoder(_alloc)
    , rotations(0)
    , on(false)  {
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _Rencoder_type;
  _Rencoder_type Rencoder;

   typedef int16_t _rotations_type;
  _rotations_type rotations;

   typedef uint8_t _on_type;
  _on_type on;




  typedef boost::shared_ptr< ::ros_lab2task2a::Rencoder_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_lab2task2a::Rencoder_<ContainerAllocator> const> ConstPtr;

}; // struct Rencoder_

typedef ::ros_lab2task2a::Rencoder_<std::allocator<void> > Rencoder;

typedef boost::shared_ptr< ::ros_lab2task2a::Rencoder > RencoderPtr;
typedef boost::shared_ptr< ::ros_lab2task2a::Rencoder const> RencoderConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_lab2task2a::Rencoder_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_lab2task2a::Rencoder_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ros_lab2task2a

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'ros_lab2task2a': ['/home/upf/code/catkin_ws/src/ros_lab2task2a/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ros_lab2task2a::Rencoder_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_lab2task2a::Rencoder_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_lab2task2a::Rencoder_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_lab2task2a::Rencoder_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_lab2task2a::Rencoder_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_lab2task2a::Rencoder_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_lab2task2a::Rencoder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "13e14eaf39e9c1e8e0f514916f5f8fb6";
  }

  static const char* value(const ::ros_lab2task2a::Rencoder_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x13e14eaf39e9c1e8ULL;
  static const uint64_t static_value2 = 0xe0f514916f5f8fb6ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_lab2task2a::Rencoder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_lab2task2a/Rencoder";
  }

  static const char* value(const ::ros_lab2task2a::Rencoder_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_lab2task2a::Rencoder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header Rencoder\n\
int16 rotations\n\
bool on\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::ros_lab2task2a::Rencoder_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_lab2task2a::Rencoder_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Rencoder);
      stream.next(m.rotations);
      stream.next(m.on);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Rencoder_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_lab2task2a::Rencoder_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_lab2task2a::Rencoder_<ContainerAllocator>& v)
  {
    s << indent << "Rencoder: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.Rencoder);
    s << indent << "rotations: ";
    Printer<int16_t>::stream(s, indent + "  ", v.rotations);
    s << indent << "on: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.on);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_LAB2TASK2A_MESSAGE_RENCODER_H
