/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/upf/code/catkin_ws/src/ros_lab2task2/srv/RbuttonStatus.srv
 *
 */


#ifndef ROS_LAB2TASK2_MESSAGE_RBUTTONSTATUSRESPONSE_H
#define ROS_LAB2TASK2_MESSAGE_RBUTTONSTATUSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_lab2task2
{
template <class ContainerAllocator>
struct RbuttonStatusResponse_
{
  typedef RbuttonStatusResponse_<ContainerAllocator> Type;

  RbuttonStatusResponse_()
    : left_pressed(false)
    , right_pressed(false)  {
    }
  RbuttonStatusResponse_(const ContainerAllocator& _alloc)
    : left_pressed(false)
    , right_pressed(false)  {
    }



   typedef uint8_t _left_pressed_type;
  _left_pressed_type left_pressed;

   typedef uint8_t _right_pressed_type;
  _right_pressed_type right_pressed;




  typedef boost::shared_ptr< ::ros_lab2task2::RbuttonStatusResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_lab2task2::RbuttonStatusResponse_<ContainerAllocator> const> ConstPtr;

}; // struct RbuttonStatusResponse_

typedef ::ros_lab2task2::RbuttonStatusResponse_<std::allocator<void> > RbuttonStatusResponse;

typedef boost::shared_ptr< ::ros_lab2task2::RbuttonStatusResponse > RbuttonStatusResponsePtr;
typedef boost::shared_ptr< ::ros_lab2task2::RbuttonStatusResponse const> RbuttonStatusResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_lab2task2::RbuttonStatusResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_lab2task2::RbuttonStatusResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ros_lab2task2

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'ros_lab2task2': ['/home/upf/code/catkin_ws/src/ros_lab2task2/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ros_lab2task2::RbuttonStatusResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_lab2task2::RbuttonStatusResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_lab2task2::RbuttonStatusResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_lab2task2::RbuttonStatusResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_lab2task2::RbuttonStatusResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_lab2task2::RbuttonStatusResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_lab2task2::RbuttonStatusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e9084cbdc2bffe2899fcce39fcb32066";
  }

  static const char* value(const ::ros_lab2task2::RbuttonStatusResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe9084cbdc2bffe28ULL;
  static const uint64_t static_value2 = 0x99fcce39fcb32066ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_lab2task2::RbuttonStatusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_lab2task2/RbuttonStatusResponse";
  }

  static const char* value(const ::ros_lab2task2::RbuttonStatusResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_lab2task2::RbuttonStatusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool left_pressed\n\
bool right_pressed\n\
\n\
";
  }

  static const char* value(const ::ros_lab2task2::RbuttonStatusResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_lab2task2::RbuttonStatusResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.left_pressed);
      stream.next(m.right_pressed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct RbuttonStatusResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_lab2task2::RbuttonStatusResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_lab2task2::RbuttonStatusResponse_<ContainerAllocator>& v)
  {
    s << indent << "left_pressed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.left_pressed);
    s << indent << "right_pressed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.right_pressed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_LAB2TASK2_MESSAGE_RBUTTONSTATUSRESPONSE_H
