/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/upf/code/catkin_ws/src/turtle_sensor_poster/srv/TurtlePosition.srv
 *
 */


#ifndef TURTLE_SENSOR_POSTER_MESSAGE_TURTLEPOSITIONRESPONSE_H
#define TURTLE_SENSOR_POSTER_MESSAGE_TURTLEPOSITIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace turtle_sensor_poster
{
template <class ContainerAllocator>
struct TurtlePositionResponse_
{
  typedef TurtlePositionResponse_<ContainerAllocator> Type;

  TurtlePositionResponse_()
    : x(0)
    , y(0)
    , theta(0.0)  {
    }
  TurtlePositionResponse_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)
    , theta(0.0)  {
    }



   typedef int64_t _x_type;
  _x_type x;

   typedef int64_t _y_type;
  _y_type y;

   typedef double _theta_type;
  _theta_type theta;




  typedef boost::shared_ptr< ::turtle_sensor_poster::TurtlePositionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtle_sensor_poster::TurtlePositionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct TurtlePositionResponse_

typedef ::turtle_sensor_poster::TurtlePositionResponse_<std::allocator<void> > TurtlePositionResponse;

typedef boost::shared_ptr< ::turtle_sensor_poster::TurtlePositionResponse > TurtlePositionResponsePtr;
typedef boost::shared_ptr< ::turtle_sensor_poster::TurtlePositionResponse const> TurtlePositionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtle_sensor_poster::TurtlePositionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtle_sensor_poster::TurtlePositionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace turtle_sensor_poster

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::turtle_sensor_poster::TurtlePositionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtle_sensor_poster::TurtlePositionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtle_sensor_poster::TurtlePositionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtle_sensor_poster::TurtlePositionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtle_sensor_poster::TurtlePositionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtle_sensor_poster::TurtlePositionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtle_sensor_poster::TurtlePositionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2b71e7da7070ce1a7abc2fb513bda0ec";
  }

  static const char* value(const ::turtle_sensor_poster::TurtlePositionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2b71e7da7070ce1aULL;
  static const uint64_t static_value2 = 0x7abc2fb513bda0ecULL;
};

template<class ContainerAllocator>
struct DataType< ::turtle_sensor_poster::TurtlePositionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtle_sensor_poster/TurtlePositionResponse";
  }

  static const char* value(const ::turtle_sensor_poster::TurtlePositionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtle_sensor_poster::TurtlePositionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 x\n\
int64 y\n\
float64 theta\n\
\n\
";
  }

  static const char* value(const ::turtle_sensor_poster::TurtlePositionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtle_sensor_poster::TurtlePositionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.theta);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct TurtlePositionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtle_sensor_poster::TurtlePositionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turtle_sensor_poster::TurtlePositionResponse_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<int64_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int64_t>::stream(s, indent + "  ", v.y);
    s << indent << "theta: ";
    Printer<double>::stream(s, indent + "  ", v.theta);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURTLE_SENSOR_POSTER_MESSAGE_TURTLEPOSITIONRESPONSE_H
