/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/upf/code/catkin_ws/src/lpmayos_ros_webots_epuck_nxt_differential_robot/srv/RbuttonStatus.srv
 *
 */


#ifndef LPMAYOS_ROS_WEBOTS_EPUCK_NXT_DIFFERENTIAL_ROBOT_MESSAGE_RBUTTONSTATUSRESPONSE_H
#define LPMAYOS_ROS_WEBOTS_EPUCK_NXT_DIFFERENTIAL_ROBOT_MESSAGE_RBUTTONSTATUSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lpmayos_ros_webots_epuck_nxt_differential_robot
{
template <class ContainerAllocator>
struct RbuttonStatusResponse_
{
  typedef RbuttonStatusResponse_<ContainerAllocator> Type;

  RbuttonStatusResponse_()
    : left_pressed(false)
    , right_pressed(false)
    , sonar(0)
    , light(0)  {
    }
  RbuttonStatusResponse_(const ContainerAllocator& _alloc)
    : left_pressed(false)
    , right_pressed(false)
    , sonar(0)
    , light(0)  {
    }



   typedef uint8_t _left_pressed_type;
  _left_pressed_type left_pressed;

   typedef uint8_t _right_pressed_type;
  _right_pressed_type right_pressed;

   typedef uint32_t _sonar_type;
  _sonar_type sonar;

   typedef uint32_t _light_type;
  _light_type light;




  typedef boost::shared_ptr< ::lpmayos_ros_webots_epuck_nxt_differential_robot::RbuttonStatusResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lpmayos_ros_webots_epuck_nxt_differential_robot::RbuttonStatusResponse_<ContainerAllocator> const> ConstPtr;

}; // struct RbuttonStatusResponse_

typedef ::lpmayos_ros_webots_epuck_nxt_differential_robot::RbuttonStatusResponse_<std::allocator<void> > RbuttonStatusResponse;

typedef boost::shared_ptr< ::lpmayos_ros_webots_epuck_nxt_differential_robot::RbuttonStatusResponse > RbuttonStatusResponsePtr;
typedef boost::shared_ptr< ::lpmayos_ros_webots_epuck_nxt_differential_robot::RbuttonStatusResponse const> RbuttonStatusResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lpmayos_ros_webots_epuck_nxt_differential_robot::RbuttonStatusResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lpmayos_ros_webots_epuck_nxt_differential_robot::RbuttonStatusResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace lpmayos_ros_webots_epuck_nxt_differential_robot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'lpmayos_ros_webots_epuck_nxt_differential_robot': ['/home/upf/code/catkin_ws/src/lpmayos_ros_webots_epuck_nxt_differential_robot/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::lpmayos_ros_webots_epuck_nxt_differential_robot::RbuttonStatusResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lpmayos_ros_webots_epuck_nxt_differential_robot::RbuttonStatusResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lpmayos_ros_webots_epuck_nxt_differential_robot::RbuttonStatusResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lpmayos_ros_webots_epuck_nxt_differential_robot::RbuttonStatusResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lpmayos_ros_webots_epuck_nxt_differential_robot::RbuttonStatusResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lpmayos_ros_webots_epuck_nxt_differential_robot::RbuttonStatusResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lpmayos_ros_webots_epuck_nxt_differential_robot::RbuttonStatusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3fcbc751b1d12b64a9eafc04beea4662";
  }

  static const char* value(const ::lpmayos_ros_webots_epuck_nxt_differential_robot::RbuttonStatusResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3fcbc751b1d12b64ULL;
  static const uint64_t static_value2 = 0xa9eafc04beea4662ULL;
};

template<class ContainerAllocator>
struct DataType< ::lpmayos_ros_webots_epuck_nxt_differential_robot::RbuttonStatusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lpmayos_ros_webots_epuck_nxt_differential_robot/RbuttonStatusResponse";
  }

  static const char* value(const ::lpmayos_ros_webots_epuck_nxt_differential_robot::RbuttonStatusResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lpmayos_ros_webots_epuck_nxt_differential_robot::RbuttonStatusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool left_pressed\n\
bool right_pressed\n\
uint32 sonar\n\
uint32 light\n\
\n\
";
  }

  static const char* value(const ::lpmayos_ros_webots_epuck_nxt_differential_robot::RbuttonStatusResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lpmayos_ros_webots_epuck_nxt_differential_robot::RbuttonStatusResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.left_pressed);
      stream.next(m.right_pressed);
      stream.next(m.sonar);
      stream.next(m.light);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct RbuttonStatusResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lpmayos_ros_webots_epuck_nxt_differential_robot::RbuttonStatusResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lpmayos_ros_webots_epuck_nxt_differential_robot::RbuttonStatusResponse_<ContainerAllocator>& v)
  {
    s << indent << "left_pressed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.left_pressed);
    s << indent << "right_pressed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.right_pressed);
    s << indent << "sonar: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.sonar);
    s << indent << "light: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.light);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LPMAYOS_ROS_WEBOTS_EPUCK_NXT_DIFFERENTIAL_ROBOT_MESSAGE_RBUTTONSTATUSRESPONSE_H
