/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/upf/code/catkin_ws/src/lpmayos_ros_webots_epuck_nxt_differential_robot/msg/Rrobot.msg
 *
 */


#ifndef LPMAYOS_ROS_WEBOTS_EPUCK_NXT_DIFFERENTIAL_ROBOT_MESSAGE_RROBOT_H
#define LPMAYOS_ROS_WEBOTS_EPUCK_NXT_DIFFERENTIAL_ROBOT_MESSAGE_RROBOT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <lpmayos_ros_webots_epuck_nxt_differential_robot/Rmotor.h>
#include <lpmayos_ros_webots_epuck_nxt_differential_robot/Rmotor.h>
#include <lpmayos_ros_webots_epuck_nxt_differential_robot/Rbutton.h>
#include <lpmayos_ros_webots_epuck_nxt_differential_robot/Rbutton.h>
#include <lpmayos_ros_webots_epuck_nxt_differential_robot/Rsonar.h>

namespace lpmayos_ros_webots_epuck_nxt_differential_robot
{
template <class ContainerAllocator>
struct Rrobot_
{
  typedef Rrobot_<ContainerAllocator> Type;

  Rrobot_()
    : Rrobot()
    , leftMotor()
    , rightMotor()
    , leftButtonSwitch()
    , rightButtonSwitch()
    , sonarSwitch()  {
    }
  Rrobot_(const ContainerAllocator& _alloc)
    : Rrobot(_alloc)
    , leftMotor(_alloc)
    , rightMotor(_alloc)
    , leftButtonSwitch(_alloc)
    , rightButtonSwitch(_alloc)
    , sonarSwitch(_alloc)  {
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _Rrobot_type;
  _Rrobot_type Rrobot;

   typedef  ::lpmayos_ros_webots_epuck_nxt_differential_robot::Rmotor_<ContainerAllocator>  _leftMotor_type;
  _leftMotor_type leftMotor;

   typedef  ::lpmayos_ros_webots_epuck_nxt_differential_robot::Rmotor_<ContainerAllocator>  _rightMotor_type;
  _rightMotor_type rightMotor;

   typedef  ::lpmayos_ros_webots_epuck_nxt_differential_robot::Rbutton_<ContainerAllocator>  _leftButtonSwitch_type;
  _leftButtonSwitch_type leftButtonSwitch;

   typedef  ::lpmayos_ros_webots_epuck_nxt_differential_robot::Rbutton_<ContainerAllocator>  _rightButtonSwitch_type;
  _rightButtonSwitch_type rightButtonSwitch;

   typedef  ::lpmayos_ros_webots_epuck_nxt_differential_robot::Rsonar_<ContainerAllocator>  _sonarSwitch_type;
  _sonarSwitch_type sonarSwitch;




  typedef boost::shared_ptr< ::lpmayos_ros_webots_epuck_nxt_differential_robot::Rrobot_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lpmayos_ros_webots_epuck_nxt_differential_robot::Rrobot_<ContainerAllocator> const> ConstPtr;

}; // struct Rrobot_

typedef ::lpmayos_ros_webots_epuck_nxt_differential_robot::Rrobot_<std::allocator<void> > Rrobot;

typedef boost::shared_ptr< ::lpmayos_ros_webots_epuck_nxt_differential_robot::Rrobot > RrobotPtr;
typedef boost::shared_ptr< ::lpmayos_ros_webots_epuck_nxt_differential_robot::Rrobot const> RrobotConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lpmayos_ros_webots_epuck_nxt_differential_robot::Rrobot_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lpmayos_ros_webots_epuck_nxt_differential_robot::Rrobot_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace lpmayos_ros_webots_epuck_nxt_differential_robot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'lpmayos_ros_webots_epuck_nxt_differential_robot': ['/home/upf/code/catkin_ws/src/lpmayos_ros_webots_epuck_nxt_differential_robot/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::lpmayos_ros_webots_epuck_nxt_differential_robot::Rrobot_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lpmayos_ros_webots_epuck_nxt_differential_robot::Rrobot_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lpmayos_ros_webots_epuck_nxt_differential_robot::Rrobot_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lpmayos_ros_webots_epuck_nxt_differential_robot::Rrobot_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lpmayos_ros_webots_epuck_nxt_differential_robot::Rrobot_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lpmayos_ros_webots_epuck_nxt_differential_robot::Rrobot_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lpmayos_ros_webots_epuck_nxt_differential_robot::Rrobot_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e68c02680c65c2559ba1f596201d8590";
  }

  static const char* value(const ::lpmayos_ros_webots_epuck_nxt_differential_robot::Rrobot_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe68c02680c65c255ULL;
  static const uint64_t static_value2 = 0x9ba1f596201d8590ULL;
};

template<class ContainerAllocator>
struct DataType< ::lpmayos_ros_webots_epuck_nxt_differential_robot::Rrobot_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lpmayos_ros_webots_epuck_nxt_differential_robot/Rrobot";
  }

  static const char* value(const ::lpmayos_ros_webots_epuck_nxt_differential_robot::Rrobot_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lpmayos_ros_webots_epuck_nxt_differential_robot::Rrobot_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header Rrobot\n\
lpmayos_ros_webots_epuck_nxt_differential_robot/Rmotor leftMotor\n\
lpmayos_ros_webots_epuck_nxt_differential_robot/Rmotor rightMotor\n\
lpmayos_ros_webots_epuck_nxt_differential_robot/Rbutton leftButtonSwitch\n\
lpmayos_ros_webots_epuck_nxt_differential_robot/Rbutton rightButtonSwitch\n\
lpmayos_ros_webots_epuck_nxt_differential_robot/Rsonar sonarSwitch\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: lpmayos_ros_webots_epuck_nxt_differential_robot/Rmotor\n\
Header Rmotor\n\
uint32 power\n\
\n\
================================================================================\n\
MSG: lpmayos_ros_webots_epuck_nxt_differential_robot/Rbutton\n\
Header Rbutton\n\
bool on\n\
\n\
================================================================================\n\
MSG: lpmayos_ros_webots_epuck_nxt_differential_robot/Rsonar\n\
Header Rsonar\n\
bool on\n\
";
  }

  static const char* value(const ::lpmayos_ros_webots_epuck_nxt_differential_robot::Rrobot_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lpmayos_ros_webots_epuck_nxt_differential_robot::Rrobot_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Rrobot);
      stream.next(m.leftMotor);
      stream.next(m.rightMotor);
      stream.next(m.leftButtonSwitch);
      stream.next(m.rightButtonSwitch);
      stream.next(m.sonarSwitch);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Rrobot_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lpmayos_ros_webots_epuck_nxt_differential_robot::Rrobot_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lpmayos_ros_webots_epuck_nxt_differential_robot::Rrobot_<ContainerAllocator>& v)
  {
    s << indent << "Rrobot: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.Rrobot);
    s << indent << "leftMotor: ";
    s << std::endl;
    Printer< ::lpmayos_ros_webots_epuck_nxt_differential_robot::Rmotor_<ContainerAllocator> >::stream(s, indent + "  ", v.leftMotor);
    s << indent << "rightMotor: ";
    s << std::endl;
    Printer< ::lpmayos_ros_webots_epuck_nxt_differential_robot::Rmotor_<ContainerAllocator> >::stream(s, indent + "  ", v.rightMotor);
    s << indent << "leftButtonSwitch: ";
    s << std::endl;
    Printer< ::lpmayos_ros_webots_epuck_nxt_differential_robot::Rbutton_<ContainerAllocator> >::stream(s, indent + "  ", v.leftButtonSwitch);
    s << indent << "rightButtonSwitch: ";
    s << std::endl;
    Printer< ::lpmayos_ros_webots_epuck_nxt_differential_robot::Rbutton_<ContainerAllocator> >::stream(s, indent + "  ", v.rightButtonSwitch);
    s << indent << "sonarSwitch: ";
    s << std::endl;
    Printer< ::lpmayos_ros_webots_epuck_nxt_differential_robot::Rsonar_<ContainerAllocator> >::stream(s, indent + "  ", v.sonarSwitch);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LPMAYOS_ROS_WEBOTS_EPUCK_NXT_DIFFERENTIAL_ROBOT_MESSAGE_RROBOT_H
