/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/upf/code/catkin_ws/src/lpmayos_ros_webots_epuck_nxt_differential_robot/msg/Rsonar.msg
 *
 */


#ifndef LPMAYOS_ROS_WEBOTS_EPUCK_NXT_DIFFERENTIAL_ROBOT_MESSAGE_RSONAR_H
#define LPMAYOS_ROS_WEBOTS_EPUCK_NXT_DIFFERENTIAL_ROBOT_MESSAGE_RSONAR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace lpmayos_ros_webots_epuck_nxt_differential_robot
{
template <class ContainerAllocator>
struct Rsonar_
{
  typedef Rsonar_<ContainerAllocator> Type;

  Rsonar_()
    : Rsonar()
    , on(false)  {
    }
  Rsonar_(const ContainerAllocator& _alloc)
    : Rsonar(_alloc)
    , on(false)  {
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _Rsonar_type;
  _Rsonar_type Rsonar;

   typedef uint8_t _on_type;
  _on_type on;




  typedef boost::shared_ptr< ::lpmayos_ros_webots_epuck_nxt_differential_robot::Rsonar_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lpmayos_ros_webots_epuck_nxt_differential_robot::Rsonar_<ContainerAllocator> const> ConstPtr;

}; // struct Rsonar_

typedef ::lpmayos_ros_webots_epuck_nxt_differential_robot::Rsonar_<std::allocator<void> > Rsonar;

typedef boost::shared_ptr< ::lpmayos_ros_webots_epuck_nxt_differential_robot::Rsonar > RsonarPtr;
typedef boost::shared_ptr< ::lpmayos_ros_webots_epuck_nxt_differential_robot::Rsonar const> RsonarConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lpmayos_ros_webots_epuck_nxt_differential_robot::Rsonar_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lpmayos_ros_webots_epuck_nxt_differential_robot::Rsonar_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace lpmayos_ros_webots_epuck_nxt_differential_robot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'lpmayos_ros_webots_epuck_nxt_differential_robot': ['/home/upf/code/catkin_ws/src/lpmayos_ros_webots_epuck_nxt_differential_robot/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::lpmayos_ros_webots_epuck_nxt_differential_robot::Rsonar_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lpmayos_ros_webots_epuck_nxt_differential_robot::Rsonar_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lpmayos_ros_webots_epuck_nxt_differential_robot::Rsonar_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lpmayos_ros_webots_epuck_nxt_differential_robot::Rsonar_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lpmayos_ros_webots_epuck_nxt_differential_robot::Rsonar_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lpmayos_ros_webots_epuck_nxt_differential_robot::Rsonar_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lpmayos_ros_webots_epuck_nxt_differential_robot::Rsonar_<ContainerAllocator> >
{
  static const char* value()
  {
    return "63445e2d1434c01535d6ecc2c857e9d8";
  }

  static const char* value(const ::lpmayos_ros_webots_epuck_nxt_differential_robot::Rsonar_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x63445e2d1434c015ULL;
  static const uint64_t static_value2 = 0x35d6ecc2c857e9d8ULL;
};

template<class ContainerAllocator>
struct DataType< ::lpmayos_ros_webots_epuck_nxt_differential_robot::Rsonar_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lpmayos_ros_webots_epuck_nxt_differential_robot/Rsonar";
  }

  static const char* value(const ::lpmayos_ros_webots_epuck_nxt_differential_robot::Rsonar_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lpmayos_ros_webots_epuck_nxt_differential_robot::Rsonar_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header Rsonar\n\
bool on\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::lpmayos_ros_webots_epuck_nxt_differential_robot::Rsonar_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lpmayos_ros_webots_epuck_nxt_differential_robot::Rsonar_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Rsonar);
      stream.next(m.on);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Rsonar_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lpmayos_ros_webots_epuck_nxt_differential_robot::Rsonar_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lpmayos_ros_webots_epuck_nxt_differential_robot::Rsonar_<ContainerAllocator>& v)
  {
    s << indent << "Rsonar: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.Rsonar);
    s << indent << "on: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.on);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LPMAYOS_ROS_WEBOTS_EPUCK_NXT_DIFFERENTIAL_ROBOT_MESSAGE_RSONAR_H
